version: "3.8"

services:
  offer_hub_database:
    image: postgres:15
    container_name: offer_hub_database
    restart: always
    environment:
      POSTGRES_USER: offerhub_admin
      POSTGRES_PASSWORD: offerhub_pass
      POSTGRES_DB: offer_hub_database
    ports:
      - "5432:5432"
    volumes:
      - offer_hub_db_data:/var/lib/postgresql/data

  offer_hub_hasura:
    image: hasura/graphql-engine:v2.40.0
    container_name: offer_hub_hasura
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://offerhub_admin:offerhub_pass@offer_hub_database:5432/offer_hub_database
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: offerhub_secret
    depends_on:
      - offer_hub_database
    ports:
      - "8080:8080"

  offer_hub_backend:
    build: .
    container_name: offer_hub_backend
    restart: always
    environment:
      DATABASE_HOST: offer_hub_database
      DATABASE_PORT: 5432
      DATABASE_USER: offerhub_admin
      DATABASE_PASSWORD: offerhub_pass
      DATABASE_NAME: offer_hub_database
    depends_on:
      - offer_hub_database
    ports:
      - "3001:3001"

volumes:
  offer_hub_db_data: {}
